run:
  timeout: 5m
  skip-dirs:
    - vendor

linters:
  disable-all: true
  enable:
    - revive          # Строгий стиль и читаемость
    - staticcheck     # Поиск багов и устаревшего кода
    - errcheck       # Проверка необработанных ошибок
    - gosec          # Проверка безопасности
    - gofmt          # Форматирование кода
    - unused         # Неиспользуемые переменные/функции
    - ineffassign    # Неэффективные присваивания
    - misspell       # Опечатки в комментариях и строках

linters-settings:
  revive:
    rules:
      - name: var-naming
        severity: warning
      - name: exported
        severity: warning
  gosec:
    excludes:
      - G104  # Игнорировать необработанные ошибки в некоторых случаях