apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    uid: DS_POSTGRESQL
    access: proxy
    url: postgres:5432
    database: grok_metrics
    user: postgres
    isDefault: true
    editable: true
    secureJsonData:
      password: password
    jsonData:
      sslmode: 'disable'
      maxOpenConns: 0
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
