app:
  name: ticker-service
  version: 1.0.0
  environment: ${ENVIRONMENT:-development}

logger:
  level: 'info'
  development: true
  encoding: console
  output_paths:
    - stdout

telegram:
  enabled: true
  token: 7647300184:AAEA2rfO9Q07psvcgjDpfAdWHcNIqdvr_Hg
  chat_id: -1002621259960

bybit:
  api_key: ""
  api_secret: ""
